/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    media: Media;
    departments: Department;
    members: Member;
    services: Service;
    'attendance-records': AttendanceRecord;
    'service-reports': ServiceReport;
    'report-instructions': ReportInstruction;
    'report-templates': ReportTemplate;
    'birthday-notification-logs': BirthdayNotificationLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'attendance-records': AttendanceRecordsSelect<false> | AttendanceRecordsSelect<true>;
    'service-reports': ServiceReportsSelect<false> | ServiceReportsSelect<true>;
    'report-instructions': ReportInstructionsSelect<false> | ReportInstructionsSelect<true>;
    'report-templates': ReportTemplatesSelect<false> | ReportTemplatesSelect<true>;
    'birthday-notification-logs': BirthdayNotificationLogsSelect<false> | BirthdayNotificationLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'birthday-notification-settings': BirthdayNotificationSetting;
  };
  globalsSelect: {
    'birthday-notification-settings': BirthdayNotificationSettingsSelect<false> | BirthdayNotificationSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name: string;
  roles: ('admin' | 'staff' | 'department-lead' | 'absentee-viewer')[];
  isSuperAdmin?: boolean | null;
  department?: (number | null) | Department;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  name: string;
  slug?: string | null;
  description?: string | null;
  reportingChannel?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Original Django media path retained during import when the file is not available locally.
   */
  legacyPath?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  firstName: string;
  middleName?: string | null;
  lastName: string;
  fullName?: string | null;
  email?: string | null;
  phoneNumber?: string | null;
  whatsappNumber?: string | null;
  department?: (number | null) | Department;
  preferredDepartment?: (number | null) | Department;
  isNewComer?: boolean | null;
  dateOfBirth?: string | null;
  dateJoined?: string | null;
  profilePicture?: (number | null) | Media;
  /**
   * Original Django profile image path retained when no local media file was imported.
   */
  legacyProfilePictureUrl?: string | null;
  nickname?: string | null;
  nationality?: string | null;
  tribe?: string | null;
  maritalStatus?: string | null;
  instagramHandle?: string | null;
  facebookHandle?: string | null;
  xHandle?: string | null;
  homeAddress?: string | null;
  bornAgain?: boolean | null;
  yearsAChristian?: string | null;
  previousChurch?: string | null;
  wantsDepartment?: boolean | null;
  occupation?: string | null;
  institution?: string | null;
  course?: string | null;
  company?: string | null;
  role?: string | null;
  skills?: string | null;
  hobbies?: string | null;
  favoriteVerse?: string | null;
  churchInterests?: string | null;
  availableDays?: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday')[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  serviceType: 'sunday-service' | 'midweek-service' | 'prayer-meeting' | 'special-program' | 'other';
  date: string;
  startTime?: string | null;
  endTime?: string | null;
  notes?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance-records".
 */
export interface AttendanceRecord {
  id: number;
  member: number | Member;
  service?: (number | null) | Service;
  date: string;
  present?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-reports".
 */
export interface ServiceReport {
  id: number;
  title: string;
  service: number | Service;
  department: number | Department;
  submittedBy?: (number | null) | Admin;
  reportContent: string;
  departmentAttendance?: number | null;
  volunteersCount?: number | null;
  attachmentUrl?: string | null;
  isApproved?: boolean | null;
  approvedBy?: (number | null) | Admin;
  approvedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "report-instructions".
 */
export interface ReportInstruction {
  id: number;
  title: string;
  department: number | Department;
  content: string;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "report-templates".
 */
export interface ReportTemplate {
  id: number;
  title: string;
  applicableDepartments?: (number | Department)[] | null;
  content: string;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "birthday-notification-logs".
 */
export interface BirthdayNotificationLog {
  id: number;
  runDate: string;
  member?: (number | null) | Member;
  recipientEmail?: string | null;
  status: 'sent' | 'skipped' | 'failed';
  message?: string | null;
  dryRun?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'admins';
        value: number | Admin;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'attendance-records';
        value: number | AttendanceRecord;
      } | null)
    | ({
        relationTo: 'service-reports';
        value: number | ServiceReport;
      } | null)
    | ({
        relationTo: 'report-instructions';
        value: number | ReportInstruction;
      } | null)
    | ({
        relationTo: 'report-templates';
        value: number | ReportTemplate;
      } | null)
    | ({
        relationTo: 'birthday-notification-logs';
        value: number | BirthdayNotificationLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  isSuperAdmin?: T;
  department?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  legacyPath?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  reportingChannel?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  firstName?: T;
  middleName?: T;
  lastName?: T;
  fullName?: T;
  email?: T;
  phoneNumber?: T;
  whatsappNumber?: T;
  department?: T;
  preferredDepartment?: T;
  isNewComer?: T;
  dateOfBirth?: T;
  dateJoined?: T;
  profilePicture?: T;
  legacyProfilePictureUrl?: T;
  nickname?: T;
  nationality?: T;
  tribe?: T;
  maritalStatus?: T;
  instagramHandle?: T;
  facebookHandle?: T;
  xHandle?: T;
  homeAddress?: T;
  bornAgain?: T;
  yearsAChristian?: T;
  previousChurch?: T;
  wantsDepartment?: T;
  occupation?: T;
  institution?: T;
  course?: T;
  company?: T;
  role?: T;
  skills?: T;
  hobbies?: T;
  favoriteVerse?: T;
  churchInterests?: T;
  availableDays?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  serviceType?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  notes?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attendance-records_select".
 */
export interface AttendanceRecordsSelect<T extends boolean = true> {
  member?: T;
  service?: T;
  date?: T;
  present?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-reports_select".
 */
export interface ServiceReportsSelect<T extends boolean = true> {
  title?: T;
  service?: T;
  department?: T;
  submittedBy?: T;
  reportContent?: T;
  departmentAttendance?: T;
  volunteersCount?: T;
  attachmentUrl?: T;
  isApproved?: T;
  approvedBy?: T;
  approvedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "report-instructions_select".
 */
export interface ReportInstructionsSelect<T extends boolean = true> {
  title?: T;
  department?: T;
  content?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "report-templates_select".
 */
export interface ReportTemplatesSelect<T extends boolean = true> {
  title?: T;
  applicableDepartments?: T;
  content?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "birthday-notification-logs_select".
 */
export interface BirthdayNotificationLogsSelect<T extends boolean = true> {
  runDate?: T;
  member?: T;
  recipientEmail?: T;
  status?: T;
  message?: T;
  dryRun?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "birthday-notification-settings".
 */
export interface BirthdayNotificationSetting {
  id: number;
  enabled?: boolean | null;
  /**
   * Lagos local time in HH:mm format.
   */
  sendTime?: string | null;
  /**
   * Comma or line separated email addresses for birthday run summaries.
   */
  adminNotificationEmails?: string | null;
  lastRun?: string | null;
  memberEmailSubject?: string | null;
  memberEmailBody?: string | null;
  adminSummarySubject?: string | null;
  adminSummaryBody?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "birthday-notification-settings_select".
 */
export interface BirthdayNotificationSettingsSelect<T extends boolean = true> {
  enabled?: T;
  sendTime?: T;
  adminNotificationEmails?: T;
  lastRun?: T;
  memberEmailSubject?: T;
  memberEmailBody?: T;
  adminSummarySubject?: T;
  adminSummaryBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}